sudo: required
language: python
install: "pip install -r requirements.txt -r dev-requirements.txt"

python:
  - "3.5"
  - "3.6"
  - "pypy3"

matrix:
  allow_failures:
    - python: pypy3

script:
  - flake8
  - pytest

services:
  - docker
  - postgresql

env:
  global:
    - FLASK_APP="app.py"
    - BOILERPLATEAPP_CONFIG="testing"
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres@localhost/boilerplateapp"

addons:
  - postgresql="9.4"
  - postgresql="9.5"
  - postgresql="9.6"
