sudo: required
language: python
install: "make"

python:
  - "3.6"
  - "3.7"
  - "pypy3"

matrix:
  allow_failures:
    - python: pypy3

script:
  - make lint
  - make test

services:
  - docker
  - postgresql

env:
  global:
    - FLASK_APP="app.py"
    - BOILERPLATEAPP_CONFIG="testing"
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres@localhost/boilerplateapp"

addons:
  - postgresql="9.6"
