dist: xenial
language: python

python:
  - "3.7"
  - "pypy3"

matrix:
  allow_failures:
    - python: pypy3

before_script:
  - pip install poetry

script:
  - make lint
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

services:
  - docker
  - postgresql

env:
  global:
    - FLASK_APP="app.py"
    - BOILERPLATEAPP_CONFIG="testing"
    - SQLALCHEMY_DATABASE_URI="postgresql://postgres@localhost/boilerplateapp"

addons:
  - postgresql="9.6"
